name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install node_modules
        run: bun install --no-cache

      - uses: nrwl/nx-set-shas@v4

      - name: Execute build process
        run: bun nx affected -t build

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install node_modules
        run: bun install --no-cache

      - uses: nrwl/nx-set-shas@v4

      - name: Build images
        run: bun nx affected -t docker-build
